language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
    allow_failures:
        - php: 5.5
        - php: 5.6
        - php: hhvm

sudo: false

cache:
    - $HOME/.composer/cache/files

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
