language: php

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2
    allow_failures:
        - php: hhvm

sudo: false

cache:
    - $HOME/.composer/cache/files

before_script:
  - PHP=$TRAVIS_PHP_VERSION
  - wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry composer self-update
  - sh -c 'if [ "$PHP" = "7.*" ]; then composer require --dev ocramius/generated-hydrator; fi;'
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text
