language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm

sudo: false

cache:
    - $HOME/.composer/cache/files

install:
    - travis_retry composer install

script:
    - phpunit
